### ISSUE TITLE
Crash with X11 running the control ui

### ISSUE THREAD

**Issue by Benhalor** [makers-for-life/makair-control-ui#77] opened 2020-12-25 11:27 UTC
When building the control UI on ubuntu, the following crash occurs when dragging the pointer of the mouse inside the windows :

thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::mem::uninitialized
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658
   4: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94
   5: winit::platform::platform::x11::EventsLoop::process_event
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956
   6: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:270
   7: winit::platform::platform::EventsLoop::poll_events
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:522
   8: winit::EventsLoop::poll_events
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:277
   9: makair_control::display::support::EventLoop::next
             at /home/gabriel/makair-control-ui/src/display/support.rs:34
  10: makair_control::display::events::DisplayEvents::handle
             at /home/gabriel/makair-control-ui/src/display/events.rs:53
  11: makair_control::display::drawer::DisplayDrawer::run
             at /home/gabriel/makair-control-ui/src/display/drawer.rs:118
  12: makair_control::display::window::DisplayWindow::spawn
             at /home/gabriel/makair-control-ui/src/display/window.rs:121
  13: makair_control::main
             at /home/gabriel/makair-control-ui/src/main.rs:124
  14: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Benhalor** [comment] 2020-12-25 16:35
Seems to be related to this :
https://github.com/rust-windowing/winit/issues/1773

**Comment by valeriansaliou** [comment] 2020-12-25 18:33
Yep, seems to be a bug that's not directly caused by the UI code but a third party library.

**Comment by valeriansaliou** [comment] 2020-12-26 07:46
Bumping winit requires bumping conrod_winit which requires bumping conrod, which is for now a no-go for me.

**Comment by valeriansaliou** [comment] 2020-12-28 16:25
Closing as the target window server is Wayland, and thus this is not happening on a live machine. X11 is kind of "unsupported" / not built for.

**Closed as completed by valeriansaliou** 2020-12-28 16:25 UTC
Labels: class:bug

**Comment by Benhalor** [comment] 2020-12-28 16:50
Confirmed that using Wayland on ubuntu doesnt raise the error
